server:
  servlet:
    context-path: /cesc
# spring http端口
  port: 8899
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: cesc
  #SpringBoot2根据我们自定义的建表语句创建数据库表；在resources目录下创建schema.sql文件
  datasource:
    initialization-mode: always
    jpa:
      database: MySQL
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: none
  profiles:
#   引入另外一个同路径下yml配置文件，该配置文件必须以application-开头
    active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath:com/hsj/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.hsj.entity
